# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'X_O.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton_X = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_X.setGeometry(QtCore.QRect(290, 30, 51, 20))
        self.radioButton_X.setObjectName("radioButton_X")
        self.radioButton_O = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_O.setGeometry(QtCore.QRect(380, 30, 51, 20))
        self.radioButton_O.setObjectName("radioButton_O")
        self.pushButton_new = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_new.setGeometry(QtCore.QRect(270, 340, 161, 51))
        self.pushButton_new.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 290, 121, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_X.setText(_translate("MainWindow", "X"))
        self.radioButton_O.setText(_translate("MainWindow", "O"))
        self.pushButton_new.setText(_translate("MainWindow", "Новая игра"))
