# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 241, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 241, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 241, 31))
        self.label_4.setObjectName("label_4")
        self.label_file = QtWidgets.QLabel(self.centralwidget)
        self.label_file.setGeometry(QtCore.QRect(40, 270, 711, 31))
        self.label_file.setText("")
        self.label_file.setObjectName("label_file")
        self.plainTextEdit_File = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_File.setGeometry(QtCore.QRect(160, 20, 491, 31))
        self.plainTextEdit_File.setObjectName("plainTextEdit_File")
        self.plainTextEdit_max = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_max.setGeometry(QtCore.QRect(290, 70, 481, 31))
        self.plainTextEdit_max.setObjectName("plainTextEdit_max")
        self.plainTextEdit_min = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_min.setGeometry(QtCore.QRect(290, 120, 481, 31))
        self.plainTextEdit_min.setObjectName("plainTextEdit_min")
        self.plainTextEdit_middle = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_middle.setGeometry(QtCore.QRect(290, 170, 481, 31))
        self.plainTextEdit_middle.setObjectName("plainTextEdit_middle")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(660, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Имя файла"))
        self.label_2.setText(_translate("MainWindow", "Максимальное значение:"))
        self.label_3.setText(_translate("MainWindow", "Минимальное значение:"))
        self.label_4.setText(_translate("MainWindow", "Среднее значение:"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
