# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cvadrat_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(764, 635)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 25, 41, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 30, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(400, 30, 41, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(590, 20, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_K = QtWidgets.QTextEdit(Form)
        self.textEdit_K.setGeometry(QtCore.QRect(60, 20, 104, 31))
        self.textEdit_K.setObjectName("textEdit_K")
        self.textEdit_N = QtWidgets.QTextEdit(Form)
        self.textEdit_N.setGeometry(QtCore.QRect(250, 20, 104, 31))
        self.textEdit_N.setObjectName("textEdit_N")
        self.textEdit_M = QtWidgets.QTextEdit(Form)
        self.textEdit_M.setGeometry(QtCore.QRect(450, 20, 104, 31))
        self.textEdit_M.setObjectName("textEdit_M")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "K ="))
        self.label_2.setText(_translate("Form", "N ="))
        self.label_3.setText(_translate("Form", "M ="))
        self.pushButton.setText(_translate("Form", "Рисовать"))
