# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exit_window_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Exit(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 169)
        MainWindow.setMinimumSize(QtCore.QSize(520, 169))
        MainWindow.setMaximumSize(QtCore.QSize(520, 169))
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
" background-color:rgb(255, 228, 250)\n"
"}\n"
"QLabel\n"
"{\n"
"     font: 10pt \"Segoe Script\";\n"
"     color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton\n"
"{    \n"
"     font: 10pt \"Segoe Script\";\n"
"     background-color: rgb(255, 255, 255);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-color: rgb(235, 235, 235);\n"
"     color: black;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(247, 214, 239);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(231, 200, 225);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 474, 98))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_exit_yes = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_exit_yes.setObjectName("pushButton_exit_yes")
        self.horizontalLayout.addWidget(self.pushButton_exit_yes)
        self.pushButton_exit_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_exit_cancel.setObjectName("pushButton_exit_cancel")
        self.horizontalLayout.addWidget(self.pushButton_exit_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Выход"))
        self.label.setText(_translate("MainWindow", "  Вы уверены, что хотите покинуть страницу?"))
        self.pushButton_exit_yes.setText(_translate("MainWindow", "Да"))
        self.pushButton_exit_cancel.setText(_translate("MainWindow", "Отмена"))
