# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_univ_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Univ(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 795)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1130, 795))
        MainWindow.setMaximumSize(QtCore.QSize(1130, 795))
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
" background-color:rgb(255, 228, 250)\n"
"}\n"
"QLabel\n"
"{\n"
"     font: 8pt \"Segoe Script\";\n"
"     color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton\n"
"{    \n"
"     font: 10pt \"Segoe Script\";\n"
"     background-color: rgb(255, 255, 255);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-color: rgb(235, 235, 235);\n"
"     color: black;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(247, 214, 239);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(231, 200, 225);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 20, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 951, 651))
        self.label_3.setObjectName("label_3")
        self.pushButton_list_univ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_list_univ.setGeometry(QtCore.QRect(940, 700, 171, 41))
        self.pushButton_list_univ.setObjectName("pushButton_list_univ")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список ВУЗов"))
        self.label.setText(_translate("MainWindow", "Доступные ВУЗы "))
        self.label_3.setText(_translate("MainWindow", "Город: Екатеринбург\n"
"    УрФУ имени Б.Н. Ельцина – Уральский федеральный университет имени Б.Н. Ельцина\n"
"    УрГПУ – Уральский государственный педагогический университет\n"
"    УрГЮУ – Уральский государственный юридический университет\n"
"\n"
"Город: Казань\n"
"    КФУ – Казанский (Приволжский) федеральный университет\n"
"    КНИТУ – Казанский национальный исследовательский технологический университет\n"
"    КГМУ – Казанский государственный медицинский университет\n"
"\n"
"Город: Москва\n"
"   МГУ имени М.В. Ломоносова – Московский государственный университет имени М.В. Ломоносова\n"
"   МГТУ имени Н.Э. Баумана – Московский государственный технический университет имени Н.Э. Баумана\n"
"  Первый МГМУ имени И.М. Сеченова – Первый Московский государственный медицинский университет имени И.М. Сеченова\n"
"\n"
"Город: Новосибирск\n"
"   НГУ – Новосибирский национальный исследовательский государственный университет\n"
"   НГТУ – Новосибирский государственный технический университет\n"
"   СГУГиТ – Сибирский государственный университет геосистем и технологий\n"
"\n"
"Город: Санкт - Петербург\n"
"   СПбГУ – Санкт-Петербургский государственный университет\n"
"   СПбПУ – Санкт-Петербургский политехнический университет Петра Великого\n"
"  ИТМО – Санкт-Петербургский национальный исследовательский университет информационных технологий, механики и оптики\n"
"\n"
"Город: Томск\n"
"   ТПУ – Национальный исследовательский Томский политехнический университет\n"
"   ТГУ – Национальный исследовательский Томский государственный университет\n"
"   ТГАСУ – Томский государственный архитектурно-строительный университет"))
        self.pushButton_list_univ.setText(_translate("MainWindow", "Выход"))
