# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration_window_var2_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 795)
        MainWindow.setMinimumSize(QtCore.QSize(1130, 795))
        MainWindow.setMaximumSize(QtCore.QSize(1130, 795))
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
" border-image:  url(C:/PyQt/ProjectPIY/pythonProject/site_page/fon.png)\n"
"}\n"
"\n"
"\n"
"QPushButton\n"
"{    \n"
"     font: 10pt \"Segoe Script\";\n"
"     background-color: rgb(255, 255, 255);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-color: rgb(235, 235, 235);\n"
"     color: black;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(247, 214, 239);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(231, 200, 225);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 50, 91, 81))
        self.label.setMinimumSize(QtCore.QSize(91, 81))
        self.label.setMaximumSize(QtCore.QSize(91, 81))
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"     border-image:  url(C:/PyQt/ProjectPIY/pythonProject/site_page/user7.png);\n"
"}\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(430, 340, 342, 41))
        self.pushButton_login.setMinimumSize(QtCore.QSize(342, 41))
        self.pushButton_login.setMaximumSize(QtCore.QSize(342, 41))
        self.pushButton_login.setObjectName("pushButton_login")
        self.result_reg_label = QtWidgets.QLabel(self.centralwidget)
        self.result_reg_label.setGeometry(QtCore.QRect(260, 420, 661, 31))
        self.result_reg_label.setText("")
        self.result_reg_label.setObjectName("result_reg_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 160, 602, 143))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_text_edit = QtWidgets.QTextEdit(self.layoutWidget)
        self.name_text_edit.setMinimumSize(QtCore.QSize(600, 30))
        self.name_text_edit.setMaximumSize(QtCore.QSize(600, 30))
        self.name_text_edit.setStyleSheet("")
        self.name_text_edit.setObjectName("name_text_edit")
        self.verticalLayout.addWidget(self.name_text_edit)
        self.create_login_text_edit = QtWidgets.QTextEdit(self.layoutWidget)
        self.create_login_text_edit.setMinimumSize(QtCore.QSize(600, 30))
        self.create_login_text_edit.setMaximumSize(QtCore.QSize(600, 30))
        self.create_login_text_edit.setStyleSheet("")
        self.create_login_text_edit.setObjectName("create_login_text_edit")
        self.verticalLayout.addWidget(self.create_login_text_edit)
        self.create_password_text_edit = QtWidgets.QTextEdit(self.layoutWidget)
        self.create_password_text_edit.setMinimumSize(QtCore.QSize(600, 30))
        self.create_password_text_edit.setMaximumSize(QtCore.QSize(600, 30))
        self.create_password_text_edit.setStyleSheet("")
        self.create_password_text_edit.setObjectName("create_password_text_edit")
        self.verticalLayout.addWidget(self.create_password_text_edit)
        self.confim_password_text_edit = QtWidgets.QTextEdit(self.layoutWidget)
        self.confim_password_text_edit.setMinimumSize(QtCore.QSize(600, 30))
        self.confim_password_text_edit.setMaximumSize(QtCore.QSize(600, 30))
        self.confim_password_text_edit.setStyleSheet("")
        self.confim_password_text_edit.setObjectName("confim_password_text_edit")
        self.verticalLayout.addWidget(self.confim_password_text_edit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_login.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.name_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#000000;\">введите имя</span></p></body></html>"))
        self.create_login_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#000000;\">придумайте логин</span></p></body></html>"))
        self.create_password_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#000000;\">придумайте пароль</span></p></body></html>"))
        self.confim_password_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#000000;\">подтвердите пароль</span></p></body></html>"))
