# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cvadrat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 628)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(240, 70, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 120, 91, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 20, 91, 31))
        self.label.setObjectName("label")
        self.textEdit_n = QtWidgets.QTextEdit(Form)
        self.textEdit_n.setGeometry(QtCore.QRect(340, 120, 151, 31))
        self.textEdit_n.setObjectName("textEdit_n")
        self.textEdit_side = QtWidgets.QTextEdit(Form)
        self.textEdit_side.setGeometry(QtCore.QRect(340, 20, 151, 31))
        self.textEdit_side.setObjectName("textEdit_side")
        self.textEdit_coeff = QtWidgets.QTextEdit(Form)
        self.textEdit_coeff.setGeometry(QtCore.QRect(340, 70, 151, 31))
        self.textEdit_coeff.setObjectName("textEdit_coeff")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Coeff"))
        self.label_3.setText(_translate("Form", "n"))
        self.pushButton.setText(_translate("Form", "Показать"))
        self.label.setText(_translate("Form", "Side"))
