# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormCreateTask(object):
    def setupUi(self, FormCreateTask):
        FormCreateTask.setObjectName("FormCreateTask")
        FormCreateTask.resize(549, 143)
        FormCreateTask.setMinimumSize(QtCore.QSize(132, 132))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(FormCreateTask)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(FormCreateTask)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1_create = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_create.setFont(font)
        self.label_1_create.setObjectName("label_1_create")
        self.verticalLayout.addWidget(self.label_1_create)
        self.label_2_create = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2_create.setFont(font)
        self.label_2_create.setObjectName("label_2_create")
        self.verticalLayout.addWidget(self.label_2_create)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_task_create = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_task_create.setObjectName("lineEdit_task_create")
        self.verticalLayout_2.addWidget(self.lineEdit_task_create)
        self.dateTimeEdit_create = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_create.setObjectName("dateTimeEdit_create")
        self.verticalLayout_2.addWidget(self.dateTimeEdit_create)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_1_create = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_1_create.setFont(font)
        self.pushButton_1_create.setObjectName("pushButton_1_create")
        self.horizontalLayout_2.addWidget(self.pushButton_1_create)
        self.pushButton_2_create = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2_create.setFont(font)
        self.pushButton_2_create.setObjectName("pushButton_2_create")
        self.horizontalLayout_2.addWidget(self.pushButton_2_create)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addWidget(self.groupBox)

        self.retranslateUi(FormCreateTask)
        QtCore.QMetaObject.connectSlotsByName(FormCreateTask)

    def retranslateUi(self, FormCreateTask):
        _translate = QtCore.QCoreApplication.translate
        FormCreateTask.setWindowTitle(_translate("FormCreateTask", "Cоздать задачу"))
        self.groupBox.setTitle(_translate("FormCreateTask", "Создать задачу"))
        self.label_1_create.setText(_translate("FormCreateTask", "ВВедите описание задачи"))
        self.label_2_create.setText(_translate("FormCreateTask", "ВВедите время"))
        self.pushButton_1_create.setText(_translate("FormCreateTask", "Отменить"))
        self.pushButton_2_create.setText(_translate("FormCreateTask", "Создать"))