# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cvadrat_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 601)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 41, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 30, 41, 31))
        self.label_2.setObjectName("label_2")
        self.textEdit_K = QtWidgets.QTextEdit(Form)
        self.textEdit_K.setGeometry(QtCore.QRect(60, 30, 151, 31))
        self.textEdit_K.setObjectName("textEdit_K")
        self.textEdit_N = QtWidgets.QTextEdit(Form)
        self.textEdit_N.setGeometry(QtCore.QRect(260, 30, 151, 31))
        self.textEdit_N.setObjectName("textEdit_N")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(430, 30, 141, 31))
        self.pushButton_1.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "K ="))
        self.label_2.setText(_translate("Form", "N ="))
        self.pushButton_1.setText(_translate("Form", "Рисовать"))
